optimusPrime: http://www.google.com
liveMSO: false
liveMSOLocation: 
core: nil
testsuite: /projects/Megatron/example_test_suite.yml
recurrsive: true
deleteresults: false
runtilfailure: false
exitonfailure: false

